name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install asdf dependencies
        uses: asdf-vm/actions/install@v4

      - name: Build
        run: go build -v ./...

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install asdf dependencies
        uses: asdf-vm/actions/install@v4

      - name: Test
        run: go test -v ./...
