name: lint
on:
  push:
    tags:
      - "v*"
    branches:
      - main
  pull_request:
    branches: [ main ]
permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  pull-requests: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install asdf dependencies
        uses: asdf-vm/actions/install@v3

      - name: Read the right version of golangci-lint
        id: golangci_lint_version
        run: |
          golangCiLintVersion=$(grep '^golangci-lint ' .tool-versions | awk '{print $2}')
          echo "::set-output name=golangCiLintVersion::${golangCiLintVersion}"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4.0.0
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v${{ steps.golangci_lint_version.outputs.golangCiLintVersion }}
          # Optional: working directory, useful for monorepos
          # working-directory: somedir

          # Optional: golangci-lint command line arguments.
          # args: --issues-exit-code=0
          args: --timeout 3m0s

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          only-new-issues: true